### ISSUE TITLE
Problem building ocamlfuse

### ISSUE THREAD

**Issue by magnjo** [istitov/stuff#102]
`>>> Emerging (8 of 52) dev-ml/ocamlfuse-2.7.1::stuff
 * v2.7.1_cvs2.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                    [ ok ]
>>> Unpacking source...
 * git-r3: git protocol is completely unsecure and may render the ebuild
 * easily susceptible to MITM attacks (even if used only as fallback). Please
 * use https instead.
 * [URI: git://github.com/astrada/ocamlfuse.git]
Initialized empty Git repository in /usr/portage/distfiles/git3-src/astrada_ocamlfuse.git/
 * Fetching git://github.com/astrada/ocamlfuse.git ...
git fetch git://github.com/astrada/ocamlfuse.git +HEAD:refs/git-r3/HEAD
remote: Counting objects: 178, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 178 (delta 0), reused 2 (delta 0), pack-reused 176
Receiving objects: 100% (178/178), 162.86 KiB | 450.00 KiB/s, done.
Resolving deltas: 100% (101/101), done.
From git://github.com/astrada/ocamlfuse
 * [new ref]                     -> refs/git-r3/HEAD
 * [new tag]         v2.7.1_cvs5 -> v2.7.1_cvs5
 * [new tag]         2.7.1_cvs_oasis1 -> 2.7.1_cvs_oasis1
 * [new tag]         2.7.1_cvs_oasis2 -> 2.7.1_cvs_oasis2
 * [new tag]         v2.7.1_cvs2      -> v2.7.1_cvs2
 * [new tag]         v2.7.1_cvs3      -> v2.7.1_cvs3
 * [new tag]         v2.7.1_cvs4      -> v2.7.1_cvs4
git symbolic-ref refs/git-r3/dev-ml/ocamlfuse/0/__main__ refs/git-r3/HEAD
 * Checking out git://github.com/astrada/ocamlfuse.git to /var/tmp/portage/dev-ml/ocamlfuse-2.7.1/work/ocamlfuse-2.7.1 ...
git checkout --quiet refs/git-r3/HEAD
GIT NEW branch -->
   repository:               git://github.com/astrada/ocamlfuse.git
   at the commit:            bc913a59342c1d89c828cdbe711674cef6c66f51
>>> Source unpacked in /var/tmp/portage/dev-ml/ocamlfuse-2.7.1/work
 * ERROR: dev-ml/ocamlfuse-2.7.1::stuff failed (prepare phase):
 *   The source directory '/var/tmp/portage/dev-ml/ocamlfuse-2.7.1/work/ocamlfuse-2.7.1-cvs~oasis1' doesn't exist
 * 
 * Call stack:
 *            ebuild.sh, line  776:  Called __ebuild_main 'prepare'
 *   phase-functions.sh, line 1053:  Called __dyn_prepare
 *   phase-functions.sh, line  372:  Called die
 * The specific snippet of code:
 *              die "The source directory '${S}' doesn't exist"
 * 
 * If you need support, post the output of `emerge --info '=dev-ml/ocamlfuse-2.7.1::stuff'`,
 * the complete build log and the output of `emerge -pqv '=dev-ml/ocamlfuse-2.7.1::stuff'`.
 * The complete build log is located at '/var/tmp/portage/dev-ml/ocamlfuse-2.7.1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-ml/ocamlfuse-2.7.1/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-ml/ocamlfuse-2.7.1/homedir'
 * S: '/var/tmp/portage/dev-ml/ocamlfuse-2.7.1/work/ocamlfuse-2.7.1-cvs~oasis1'

>>> Failed to emerge dev-ml/ocamlfuse-2.7.1, Log file:
`

**Comment by istitov** [comment]
repaired ebuild, check it out
