### ISSUE TITLE
qt4-r2.eclass could not be found by inherit() blocks some of the packages

### ISSUE THREAD

**Issue by prototype99** [istitov/stuff#105]
you can add it back in by two methods: 

1. advise the user to get this overlay: https://wiki.gentoo.org/wiki/Overlay:Kde-sunset

2. copy the qt4-r2.eclass file from this overlay

if you do the second method, you will probably need more than just that from the overlay, but it's a start.
affected ebuilds:

- media-video/rosa-media-player-1.0

- media-video/rosa-media-player-1.6.2

- www-plugins/rosa-media-player-plugin-0.951

- www-plugins/rosa-media-player-plugin-1.6

- sci-mathematics/fvm2-1.99.2

- dev-util/qbs-9999

- app-text/qrfcview-0.62

- app-text/qrfcview-9999

- games-roguelike/dwarftherapist-37.0.0

**Comment by prototype99** [comment]
(sorry by accident closed issue)

**Comment by alexws54tk** [comment]
I updated ebuilds to move them from `qt4-r2.eclass` to `qmake-utils.eclass`.
