### ISSUE TITLE
media-plugins/frei0r-plugins-9999 - EAPI=5 is not supported

### ISSUE THREAD

**Issue by stefantalpalaru** [istitov/stuff#127]
```text
Calculating dependencies - * ERROR: media-plugins/frei0r-plugins-9999::stuff failed (depend phase):
 *   EAPI=5 is not supported
 - * 
 * Call stack:
 *                    ebuild.sh, line 609:  Called source '/var/lib/layman/stuff/media-plugins/frei0r-plugins/frei0r-plugins-9999.ebuild'
 *   frei0r-plugins-9999.ebuild, line   5:  Called inherit 'cmake' 'multilib' 'git-r3'
 *                    ebuild.sh, line 314:  Called __qa_source '/usr/portage/eclass/cmake.eclass'
 *                    ebuild.sh, line 112:  Called source '/usr/portage/eclass/cmake.eclass'
 *                 cmake.eclass, line  99:  Called die
 * The specific snippet of code:
 *   	*) die "EAPI=${EAPI:-0} is not supported" ;;
 * 
 * If you need support, post the output of `emerge --info '=media-plugins/frei0r-plugins-9999::stuff'`,
 | * the complete build log and the output of `emerge -pqv '=media-plugins/frei0r-plugins-9999::stuff'`.
 * Working directory: '/usr/lib64/python3.6/site-packages'
 * S: '/var/tmp/portage/media-plugins/frei0r-plugins-9999/work/frei0r-plugins-9999'
```

**Comment by iadegesso** [comment]
Me too

 * ERROR: media-plugins/frei0r-plugins-9999::stuff failed (depend phase):
 *   EAPI=5 is not supported
 * 
 * Call stack:
 *                    ebuild.sh, line 609:  Called source '/var/lib/layman/stuff/media-plugins/frei0r-plugins/frei0r-plugins-9999.ebuild'
 *   frei0r-plugins-9999.ebuild, line   5:  Called inherit 'cmake' 'multilib' 'git-r3'
 *                    ebuild.sh, line 314:  Called __qa_source '/usr/portage/eclass/cmake.eclass'
 *                    ebuild.sh, line 112:  Called source '/usr/portage/eclass/cmake.eclass'
 *                 cmake.eclass, line  99:  Called die
 * The specific snippet of code:
 *   	*) die "EAPI=${EAPI:-0} is not supported" ;;
 * 
 * If you need support, post the output of `emerge --info '=media-plugins/frei0r-plugins-9999::stuff'`,
 * the complete build log and the output of `emerge -pqv '=media-plugins/frei0r-plugins-9999::stuff'`.
 * Working directory: '/usr/lib64/python3.7/site-packages'
 * S: '/tmp/portage/media-plugins/frei0r-plugins-9999/work/frei0r-plugins-9999'

**Comment by istitov** [comment]
#135
