### ISSUE TITLE
svgcleaner is not installing

### ISSUE THREAD

**Issue by LebedevV** [istitov/stuff#137]
The error is 
>>> Compiling source in /var/tmp/portage/media-gfx/svgcleaner-0.9.5/work/svgcleaner-0.9.5 ...
    Updating crates.io index
warning: spurious network error (2 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
warning: spurious network error (1 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
error: failed to get `clap` as a dependency of package `svgcleaner v0.9.5 (/var/tmp/portage/media-gfx/svgcleaner-0.9.5/work/svgcleaner-0.9.5)`
Caused by:
  failed to load source for dependency `clap`

Probably, cargo-ebuild might be helpful

**Comment by LebedevV** [comment]
Sorted with the most recent patch

**Comment by istitov** [comment]
closed in #242
