### ISSUE TITLE
doins failed

### ISSUE THREAD

**Issue by 0xseck** [istitov/stuff#143]
I was able to compile it after struggling for couple hours. But on the installing phase, I get the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: b'contrib/gobby-0.5.desktop'
 * ERROR: app-editors/gobby-0.5.0::stuff failed (install phase):
 *   doins failed
```

**Comment by LebedevV** [comment]
Hmmm, that's interesting, 'doins failed' sounds very manageable.
Could you please provide some details on that how did you solve the compilation (actually, configuration) issue?
Currently there is still an issue with libinfinity, as I can see it.

**Comment by 0xseck** [comment]
While I still can't compile it with server and gtk3 USE flags, I managed to compile it by changing  "./configure" to econf in the ebuilds. Because running configure script directly will cause libs to install under wrong folders.

Also I managed to fix "doins failed" just by fixing the .desktop file path

**Comment by 0xseck** [comment]
#144

**Comment by LebedevV** [comment]
Looks good, thank you!
