### ISSUE TITLE
deadbeef-fb compile failure fix

### ISSUE THREAD

**Issue by pensive-fuzz** [istitov/stuff#172]
deadbeef-fb uses depreciated gtk settings, which causes warning messages. Since it's Makefile.am is set to treat warnings as errors it fails. Patching the Makefile.am can at least for the moment sidestep this.

ebuild:
```
PATCHES=(
	"${FILESDIR}/${PN}-9999-makefileam.patch"
)
```

deadbeef-fb-9999-makefileam.patch:
```
+++ a/Makefile.am	2021-08-10 22:56:09.225479496 -0400
--- b/Makefile.am	2021-08-10 22:57:07.355417616 -0400
@@ -36,8 +36,6 @@
 # normal lib
 if DEBUG
 EXTRA_FLAGS = -g3 -ggdb -Wall
-else
-EXTRA_FLAGS = -Werror
 endif
 
 if HAVE_GTK2
```

Also, why are you using `${PN}-${PV}` over just using `${P}` in the makefile? As far as I'm aware they are equivalent.

**Comment by istitov** [comment]
#194 closes it as WONTFIX
