### ISSUE TITLE
dev-python/numba depends on masked package dev-python/llvmlite

### ISSUE THREAD

**Issue by redblade7** [istitov/stuff#176]
The package dev-python/numba depends on package dev-python/llvmlite, which is masked for removal on 2021-12-08.

**Comment by LebedevV** [comment]
Many thanks for letting us know, will have a look ASAP!

**Comment by LebedevV** [comment]
Just in case - llvmlite-9999 is still available in ::stuff, pretends to be working for the moment; numba is compiling.

Are there any issues with these packages for the moment?

**Comment by redblade7** [comment]
llvmlite-0.37.0 is installed fine now that it's in ::stuff
