### ISSUE TITLE
ERROR: media-libs/mlt-9999::stuff failed (configure phase)

### ISSUE THREAD

**Issue by mrturcot** [istitov/stuff#205]
Hey mlt fails to build

`source in /var/tmp/portage/media-libs/mlt-9999/work/mlt-9999 ...                          sed: can't read Makefile: No such file or directory   * ERROR: media-libs/mlt-9999::stuff failed (configure phase)
`

Build log https://pastebin.com/2fr6EWyw
emerge --info https://pastebin.com/Xy4p7EQi

Thanks!

**Comment by LebedevV** [comment]
It seems that autoconf was changed to cmake when the major version was upgraded... many thanks for pointing that out, should work now!

I harmonized -9999 with the ebuild from the main three; some functionality (lua, ruby support, etc) might not be available right now.
Please, let us know if you need something specific there.

Also, please, confirm if it works for you now.

**Comment by mrturcot** [comment]
yes we're good to go! thank you :+1:
