### ISSUE TITLE
net-p2p/acestream-engine problem

### ISSUE THREAD

**Issue by waldo-de-kard** [istitov/stuff#44]
Problem:
acestreamengine --client-gtk
gtk is not installed
Info:
emerge --info  | http://paste.org.ru/?nzf9df

Позже дам инфу по второму багу. Какая еще требуется информация?

**Comment by istitov** [comment]
@waldo-de-kard  не хочешь ебилд 3-го в **stuff** запилить?

**Comment by waldo-de-kard** [comment]
В оверлее ROKO_ валяется хрен знает какой степени работоспособности....

**Comment by istitov** [comment]
Ну, я не пользуюсь им, можешь ебилд запилить, если ace stream'ом пользуешься?

**Comment by istitov** [comment]
Closing issue, WONTFIX, ebuild has bee dropped some time ago.
