### ISSUE TITLE
problem in compiling with libeb-dev

### ISSUE THREAD

**Issue by pd1986** [istitov/stuff#46]
I tried compiling the goldendict from gtihub through ebuild, but failed with Epwing format support. I found the information from the goldendict page, here is the explanation. Please fix it. Thanks

Building without Epwing format support

If you have problem building with libeb-dev package, you can pass "CONFIG+=no_epwing_support" to qmake in order to disable Epwing format support

qmake "CONFIG+=no_epwing_support"

**Comment by istitov** [comment]
I'll look into it in next couple of days...

**Comment by istitov** [comment]
closing, as ebuild was dropped some time ago
