### ISSUE TITLE
Add repoman travis

### ISSUE THREAD

**Issue by mpkh** [istitov/stuff#70]

**Comment by istitov** [comment]
what do you want exactly?

**Comment by alexws54tk** [comment]
He said about this.
Run repoman via travis: https://github.com/mrueg/repoman-travis

**Comment by istitov** [comment]
Well... I'll give it a try.

**Comment by istitov** [comment]
OK. I tried, but it looks like you need to own a repo, a be a part of a team. The read/write access to the repo is not enough. Waiting  @megabaks to respond then...

**Comment by alexws54tk** [comment]
@istitov, I think, this issue may be closed as completed.

**Comment by istitov** [comment]
Well...
Closed, WONTFIX, unfortunately...

**Comment by istitov** [comment]
As repository has just been transferred from megabaks to me, added travis build.

**Comment by alexws54tk** [comment]
@istitov 
Напишу сюда, дабы не плодить лишних сущностей.
Оказалось, что с момента последнего обновления, Трэвис перестал отрабатывать корректно. Он просто падал. В Апстриме об этом вкурсе.
Внёс небольшие корректировки в файл Трэвиса. Теперь оно хотя бы отрабатывает, и сыплет наши ошибки.
…Кстати… надо бы выделить ещё немного времени и почистить оверлэй…

**Comment by istitov** [comment]
@alexws54tk 
Спасибо, Саш!
Да у меня уже чуть ли не год хронически не хватает времени. :(
