### ISSUE TITLE
net-libs/ortp-0.27.0 - missing dependency

### ISSUE THREAD

**Issue by stefantalpalaru** [istitov/stuff#94]
checking for bctoolbox... no
configure: error: "Could not find bctoolbox (required dependency)"

It probably needs this: http://download.savannah.nongnu.org/releases/linphone/bctoolbox/

**Comment by istitov** [comment]
thnx for pointing that out. will add in a few days.

**Comment by istitov** [comment]
should work now. sorry for such a delay.
Going to make updates for the whole linphone stack (**really**) soon

**Comment by istitov** [comment]
fixed there 327f7947d4fed9f50d548d88783e36b1fbdf9aac
