### ISSUE TITLE
Overlay maintenance

### ISSUE THREAD

**Issue by Bfgeshka** [istitov/stuff#95]
Hello there, it is a nice overlay, packages from which I'm using very often, good job.

Check this overlay with `app-portage/repoman`.
There are many warnings, some of them are critical (like 500+ entries in `dependency.bad` category).

**Comment by istitov** [comment]
Thnx for pointing out. Will do try doing it soon...

**Comment by istitov** [comment]
Ok. I fixed almost (he-he, almost) everything, so I'm closing the issue.
I'll address rest of the issues later. What packages are you using, btw?

**Comment by Bfgeshka** [comment]
I use quite a few: deadbeef, plugins for it, pf-sources, lorquotes fortune base.

Good job maintaining it, btw.

**Comment by istitov** [comment]
Thank you! I'm going to keep up with cleaning and fixing for some time. Stay tuned :-)
