### ISSUE TITLE
Upd adom ebuild

### ISSUE THREAD

**Issue by istitov** [istitov/stuff#98]
Subj.
See [ADOM](http://www.adom.de/home/downloads.html)

**Comment by LebedevV** [comment]
adom source files have been moved to somewhere (dbolical.com, I can see).
Do we really want to add these sources?
Also, currently it is available on steam

**Comment by LebedevV** [comment]
https://www.adom.de/home/download/old/ - sources are here

**Comment by istitov** [comment]
closed by #202
